#Must be copied to /etc/netplan
#Ensure permissions are:
#sudo chown root:root /etc/netplan/01-gateway.yaml
#sudo chmod 600 /etc/netplan/01-gateway.yaml

network:
  version: 2
  renderer: networkd
  ethernets:
    enp2s0:
      dhcp4: true
